### ISSUE TITLE
Add `CancellationToken cancellationToken = default` to generated Methods

### ISSUE THREAD

**Issue by kirides** [christianhelle/refitter#19]
Currently the generated code looks like this

```cs
[Post("/v1/Endpoint")]
Task EndpointPOST([Body] EndpointV1 body);
```

To support timeouts etc. it would be nice to get refitter to add the CancellationToken-parameter like this

```cs
[Post("/v1/Endpoint")]
Task EndpointPOST([Body] EndpointV1 body, CancellationToken cancellationToken = default);
```

**Comment by christianhelle** [comment]
@kirides This is trivial to implement and I can get started with this immediately. Unless you want to give it a shot yourself?

**Comment by kirides** [comment]
We're currently in the evaluation phase of deciding to use this tool to generate our clients, sadly i can't provide an implementation at this stage... _bureaucracy_

**Comment by christianhelle** [comment]
I'm currently trying this out and I can see that Refit doesn't seem to like `CancellationToken cancellationToken = default`

I generated this code

```csharp
[Get("/pet/{petId}")]
Task<Pet> GetPetById(long petId, CancellationToken cancellationToken = default);
```

But when I run it I just get a `Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.` error when I run the generated code

```
Unhandled exception. System.InvalidOperationException: ISwaggerPetstore doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.
   at Refit.RestService.GetGeneratedType(Type refitInterfaceType) in /_/Refit/RestService.cs:line 173
   at Refit.RestService.For(Type refitInterfaceType, HttpClient client, IRequestBuilder builder) in /_/Refit/RestService.cs:line 76
   at Refit.RestService.For[T](HttpClient client, IRequestBuilder`1 builder) in /_/Refit/RestService.cs:line 20
   at Refit.RestService.For[T](HttpClient client, RefitSettings settings) in /_/Refit/RestService.cs:line 34
   at Refit.RestService.For[T](String hostUrl, RefitSettings settings) in /_/Refit/RestService.cs:line 54
   at Refit.RestService.For[T](String hostUrl) in /_/Refit/RestService.cs:line 65
   at MyNamespace.Program.TestPetstoreUsingDirectTypes() in C:\projects\christianhelle\refitter\test\ConsoleApp\Program.cs:line 34
   at MyNamespace.Program.Main(String[] args) in C:\projects\christianhelle\refitter\test\ConsoleApp\Program.cs:line 11
   at MyNamespace.Program.<Main>(String[] args)
```

I'm investigating as why this is

**Comment by kirides** [comment]
Sounds interesting, manually specifying it in a .NET 6.0 project works fine.

Here is the code from refit that checks for its existence (many places call that, and other chains also check for its existence)
https://github.com/reactiveui/refit/blob/ef463956936fcdfd248d120672fe0bb7ff93d5ac/Refit/RequestBuilderImplementation.cs#L474

**Comment by christianhelle** [comment]
@kirides did you get the interface containing a `CancellationToken` in the arguments to work? I have no luck with this. I already have the code for generating an interface that uses `CancellationToken` as the last argument but I can't get the interface to work

**Comment by kirides** [comment]
Using Refit `6.3.2` this works flawlessly:

![image](https://user-images.githubusercontent.com/13602143/234555390-fda7b3b2-9cb9-48af-bea9-ec160a5af1fb.png)

**Comment by christianhelle** [comment]
@kirides I honestly couldn't get CancellationToken to work but if you're example works then I trust on that. Generating code that uses CancellationTokens was trivial to make and I expect to release this in the afternoon
