### ISSUE TITLE
Support for OpenAPI version 3.1.0

### ISSUE THREAD

**Issue by rmunson8** [christianhelle/refitter#328]
When running against an openAPI json with version 3.1.0:

> Refitter v0.9.7.0
Support key: whx1qwy
Error:
OpenAPI specification version '3.1.0' is not supported.
Exception:
Microsoft.OpenApi.Readers.Exceptions.OpenApiUnsupportedSpecVersionException
Stack Trace:
   at Microsoft.OpenApi.Readers.ParsingContext.Parse(YamlDocument yamlDocument)
   at Microsoft.OpenApi.Readers.OpenApiYamlDocumentReader.ReadAsync(YamlDocument input, CancellationToken cancellationToken)
   at Microsoft.OpenApi.Readers.OpenApiTextReaderReader.ReadAsync(TextReader input, CancellationToken cancellationToken)
   at Microsoft.OpenApi.Readers.OpenApiStreamReader.ReadAsync(Stream input, CancellationToken cancellationToken)
   at Microsoft.OpenApi.Readers.OpenApiMultiFileReader.Read(String openApiFile, CancellationToken cancellationToken) in /home/runner/work/oasreader/oasreader/src/OasReader/OpenApiMultiFileReader.cs:line 21
   at Refitter.Validation.OpenApiValidator.Validate(String openApiFile) in /_/src/Refitter/Validation/OpenApiValidator.cs:line 13
   at Refitter.GenerateCommand.ValidateOpenApiSpec(String openApiPath) in /_/src/Refitter/GenerateCommand.cs:line 144
   at Refitter.GenerateCommand.ExecuteAsync(CommandContext context, Settings settings) in /_/src/Refitter/GenerateCommand.cs:line 72

**Comment by christianhelle** [comment]
@rmunson8 Have you tried using the `--skip-validation` option? 

Refitter uses the Microsoft OpenAPI.NET library to validate the OAS document and that library doesn't officially support OAS v3.1.0, that said, if the OAS document that you are working with doesn't use much v3.1.0 specific features, then it might work...

**Comment by rmunson8** [comment]
Thank you. I ran with `--skip-validation` and it ran successfully.  Likely weren't using any v3.1.0 specific features.
